name: test_binding
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: init submodules
        run: |
          git submodule update --init --recursive

      - name: activate environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest" 
          environment-file: environment.yml
          activate-environment: pybind11-env
        
      - name: build
        run: |
          mkdir build
          cd build
          cmake -DCI_ACTION=ON ..
          make
          cd ..

      - name: test
        run: |
          python test.py
        
      - name: add small badge (of course ;))
        run: |
          if [ $? -eq 0 ]; then
            echo "![small badge](https://img.shields.io/badge/pybind11%20test-passing-brightgreen)" > badge.md
          else
            echo "![small badge](https://img.shields.io/badge/pybind11%20test-failing-red)" > badge.md
          fi

      - name: Update README.md with badge
        run: |
          if [ -f badge.md ]; then
            sed -i.bak '/<!-- badge-placeholder -->/{n;d;}' README.md && rm README.md.bak
            sed -i.bak '/<!-- badge-placeholder -->/r badge.md' README.md && rm README.md.bak
          else
            echo "badge.md not found. Skipping README update."
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "feat: update README.md with test badge" || echo "No changes to commit"
          git push