name: test_binding
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: activate environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: pybind11-env
        
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          cd ..

      - name: test
        run: |
          python test.py
        
      - name: add small badge (of course ;))
        run: |
          if [ $? -eq 0 ]; then
            echo "![small badge](https://img.shields.io/badge/pybind11%20test-passing-brightgreen)"
          else
            echo "![small badge](https://img.shields.io/badge/pybind11%20test-failing-red)"
          fi
